cti.vonage.api_key=
cti.vonage.api_secret=
cti.vonage.application_id=change-me
cti.vonage.private_key=/app/config/private.key
cti.vonage.from_number=+39XXXXXXXXXX
cti.vonage.answer_url=https://your-domain.com/api/cti/vonage/answer
cti.vonage.event_url=https://your-domain.com/api/cti/vonage/event
cti.vonage.music_on_hold_url=https://nexmo-community.github.io/ncco-examples/assets/voice_api_audio_streaming.mp3
