vonage.application-name=change-me
vonage.application-id=change-me
vonage.api-key=change-me
vonage.api-secret=change-me
vonage.base-url=https://api.nexmo.com/v1/calls
vonage.private-key=/app/config/private.key
vonage.voice-answer-url=https://your-domain.com/api/vonage/answer
vonage.voice-event-url=https://your-domain.com/api/vonage/event
vonage.rtc-event-url=https://your-domain.com/api/vonage/event
vonage.from-number=+39XXXXXXXXXX
