CREATE TABLE chiamate (
  id                BIGSERIAL     PRIMARY KEY,
  uuid              VARCHAR(64),
  conversation_uuid VARCHAR(64),
  direction         VARCHAR(16),
  status            VARCHAR(32),
  from_type         VARCHAR(16),
  from_number       VARCHAR(32),
  to_type           VARCHAR(16),
  to_number         VARCHAR(32),
  rate              VARCHAR(16),
  price             VARCHAR(16),
  duration          INTEGER,
  start_time        TIMESTAMP,
  end_time          TIMESTAMP,
  network           VARCHAR(32),
  answer_url        TEXT,
  event_url         TEXT,
  error_title       VARCHAR(255),
  error_detail      TEXT,
  operator_id       BIGINT,
  contatto_id       BIGINT,
  created_at        TIMESTAMP DEFAULT NOW(),
  updated_at        TIMESTAMP
);
