cti.api.key=change-me-in-production
cti.vonage.base-url=https://api.nexmo.com/v1/calls
cti.vonage.application-id=change-me
cti.vonage.private-key=change-me
cti.vonage.from-number=+39XXXXXXXXXX
cti.vonage.event-url=https://your-domain.com/api/cti
cti.vonage.music-on-hold-url=https://nexmo-community.github.io/ncco-examples/assets/voice_api_audio_streaming.mp3
